/**
 * envelope.js — Animated birthday card logic.
 * All content is driven by SITE_CONFIG defined in config.js.
 * Do NOT edit this file to change content — edit config.js instead.
 */
(function () {
  'use strict';

  // ── 1. Populate content from config ──────────────────────────────────────

  var cfg = (typeof SITE_CONFIG !== 'undefined' && SITE_CONFIG.envelope) ? SITE_CONFIG.envelope : {};

  // Section heading
  var sectionTitle = document.getElementById('envelope-section-title');
  if (sectionTitle) sectionTitle.textContent = cfg.sectionTitle || 'A Special Message For You';

  // Card front title
  var frontTitle = document.getElementById('env-front-title');
  if (frontTitle) frontTitle.textContent = cfg.cardFrontTitle || 'Happy Birthday';

  // Letter content (inside the card)
  var letterContent = document.getElementById('env-letter-content');
  if (letterContent) {
    var html = '';

    // Greeting
    if (cfg.greeting) {
      html += '<p class="env-greeting">' + escapeHtml(cfg.greeting) + '</p>';
    }

    // Body paragraphs
    if (Array.isArray(cfg.paragraphs)) {
      cfg.paragraphs.forEach(function (para) {
        html += '<p>' + escapeHtml(para) + '</p>';
      });
    }

    // Sign-off
    if (cfg.signOff || cfg.senderName) {
      html += '<p class="env-signed">';
      if (cfg.signOff)   html += escapeHtml(cfg.signOff) + '<br>';
      if (cfg.senderName) html += escapeHtml(cfg.senderName);
      html += '</p>';
    }

    letterContent.innerHTML = html;
  }

  // Optional photo on the back of the card front
  var polaroidWrapper = document.getElementById('env-polaroid-wrapper');
  if (polaroidWrapper && cfg.photoPath) {
    polaroidWrapper.innerHTML =
      '<div class="env-polaroid">' +
        '<div class="env-img" style="background-image: url(\'' + cfg.photoPath + '\')"></div>' +
      '</div>';
  }

  // ── 2. Open / Close button logic ─────────────────────────────────────────

  var card   = document.getElementById('env-card');
  var openB  = document.getElementById('env-open');
  var closeB = document.getElementById('env-close');
  var timer  = null;

  if (card && openB && closeB) {
    openB.addEventListener('click', function () {
      card.setAttribute('class', 'env-open-half');
      if (timer) clearTimeout(timer);
      timer = setTimeout(function () {
        card.setAttribute('class', 'env-open-fully');
        timer = null;
      }, 1000);
    });

    closeB.addEventListener('click', function () {
      card.setAttribute('class', 'env-close-half');
      if (timer) clearTimeout(timer);
      timer = setTimeout(function () {
        card.setAttribute('class', '');
        timer = null;
      }, 1000);
    });
  }

  // ── Helper ────────────────────────────────────────────────────────────────
  function escapeHtml(str) {
    return String(str)
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;');
  }
}());
